name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  py27-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          sudo apt-get install -y krb5-config libkrb5-dev
          python -m pip install -U pip
          pip install tox

      - name: Run auto-tests (Python 2.7)
        run: tox -e py27

  standard-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get install -y krb5-config libkrb5-dev
          python -m pip install -U pip
          pip install tox

      - name: Run auto-tests (Python 3.8 + Coverage)
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: tox -e cov-ci
    
      - name: Run static analysis
        run: tox -e static

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
